### ISSUE TITLE
Integration tests for this package

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-packages/automgrp#5]
Since this package provides a standard test, I suggest to add it to the two tests that we offer to GAP package authors to test _development_ versions of their packages for compatibility with GAP stable and master branches:
- https://github.com/gap-packages/gap-docker-pkg-tests-master-devel 
- https://github.com/gap-packages/gap-docker-pkg-tests-stable-4.10-devel

The first of these two repositories has a README file with further details. To add your package to the test, please submit a pull request to add a line to the `.travis.yml` file.

**Comment by fingolfin** [comment]
@alex-konovalov the orgs in this links are wrong, should be `gap-infra` -- of course they still "work" due to redirects, but I wonder if they were copy-pasted from a source that still has old links? In that case, mght be a good idea to update that source? Also, let's not forget <https://github.com/gap-infra/gap-docker-pkg-tests-stable-4.11-devel>

I've written a script which performs these updates automatically, I'll use it to create PRs for these repos.

**Comment by fingolfin** [comment]
See here:
- https://github.com/gap-infra/gap-docker-pkg-tests-master-devel/pull/20
- https://github.com/gap-infra/gap-docker-pkg-tests-stable-4.11-devel/pull/2
- https://github.com/gap-infra/gap-docker-pkg-tests-stable-4.10-devel/pull/3

**Comment by olexandr-konovalov** [comment]
Yes, @fingolfin that was a saved comment. I will update that in my Github profile, thanks for reminding this.

**Comment by fingolfin** [comment]
Since @alex-konovalov merged my PRs, this is resolved.
